name: Stack Build and Test
on: [push, pull_request, workflow_dispatch]

jobs:
  stack-build:
    name: Stack build (+ examples)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install librdkafka and graphviz (for dot)
        run: |
          sudo apt-get update && sudo apt-get install librdkafka-dev graphviz
      - uses: freckle/stack-action@v5
        id: stack
        with:
          pedantic: false
          stack-arguments: --no-haddock-deps --haddock
          cache-prefix: v2

      - name: Build examples
        run: |
          ./gen_test_makefile.sh > Makefile
          make

      - if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        name: Setup Pages
        uses: actions/configure-pages@v3

      - if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ steps.stack.outputs.dist-dir }}/doc/html/striot/

  deploy-pages:
    name: Deploy Haddock docs to GitHub Pages
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: stack-build
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
