name: Stack Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  stack-build:
    name: Stack build (+ examples)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install librdkafka and graphviz (for dot)
        run: |
          sudo apt-get update && sudo apt-get install librdkafka-dev graphviz
      - uses: freckle/stack-action@v4
        with:
          pedantic: false
      - name: Build examples
        run: |
          ./gen_test_makefile.sh > Makefile
          make
